paperless:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
      hosts:
      - host: paperless.khuedoan.com
        paths:
          - path: /
            pathType: Prefix
      tls:
      - secretName: paperless-tls-certificate
        hosts:
          - paperless.khuedoan.com
