dex:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
    hosts:
    - host: dex.khuedoan.com
      paths:
      - path: /
        pathType: ImplementationSpecific
    tls:
    - secretName: dex-tls-certificate
      hosts:
        - dex.khuedoan.com
  config:
    issuer: https://dex.khuedoan.com
    storage:
      type: kubernetes
      config:
        inCluster: true
    connectors:
    - type: gitea
      id: gitea
      name: Gitea
      config:
        clientID: $GITEA_CLIENT_ID
        clientSecret: $GITEA_CLIENT_SECRET
        redirectURI: https://dex.khuedoan.com/callback
        baseURL: https://git.khuedoan.com
