seafile:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
      hosts:
      - host: seafile.khuedoan.com
        paths:
          - path: /
            pathType: Prefix
      tls:
      - secretName: seafile-tls-certificate
        hosts:
          - seafile.khuedoan.com
  mariadb:
    enabled: true
