syncthing:
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
      hosts:
      - host: syncthing.khuedoan.com
        paths:
        - path: /
          pathType: Prefix
      tls:
      - secretName: syncthing-tls-certificate
        hosts:
        - syncthing.khuedoan.com
  persistence:
    storageClass: longhorn
    data:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteOnce
      retain: true
