[book]
authors = ["Khue Doan"]
language = "en"
multilingual = false
src = "src"
title = "Khue's Homelab"

[output.html]
git-repository-url = "https://github.com/locmai/homelab"
edit-url-template = "https://github.com/locmai/homelab/edit/master/docs/{path}"
